"""empty message

Revision ID: 18f4984e31d9
Revises: e922ab2bd828
Create Date: 2017-08-27 19:58:01.926723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18f4984e31d9'
down_revision = 'e922ab2bd828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flicket_topic', sa.Column('site_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'flicket_topic', 'site', ['site_id'], ['ID'])
    op.drop_column('flicket_topic', 'facility')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flicket_topic', sa.Column('facility', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'flicket_topic', type_='foreignkey')
    op.drop_column('flicket_topic', 'site_id')
    # ### end Alembic commands ###
