"""empty message

Revision ID: 25d20f5036bb
Revises: ae843d17da36
Create Date: 2017-08-24 18:26:03.436813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d20f5036bb'
down_revision = 'ae843d17da36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('it_asset', sa.Column('last_checked', sa.DateTime(), nullable=True))
    op.add_column('it_asset', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('it_asset', 'online')
    op.drop_column('it_asset', 'last_checked')
    # ### end Alembic commands ###
