"""empty message

Revision ID: 364ce7e16831
Revises: e92f4d9b52ef
Create Date: 2017-07-24 14:34:30.448936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364ce7e16831'
down_revision = 'e92f4d9b52ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverable_ITC_map', sa.Column('percentage_complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Deliverable_ITC_map', 'percentage_complete')
    # ### end Alembic commands ###
