"""empty message

Revision ID: 375aee4d1f5d
Revises: 9212d448882f
Create Date: 2017-05-09 15:19:43.851912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '375aee4d1f5d'
down_revision = '9212d448882f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), server_default='0', nullable=False))
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False))
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('first_name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
