"""empty message

Revision ID: 37c30892cad0
Revises: 3965209e0c1e
Create Date: 2017-07-21 19:26:20.819929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37c30892cad0'
down_revision = '3965209e0c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Check_generic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ITC_check_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_generic', sa.Integer(), nullable=True),
    sa.Column('ITC_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ITC_id'], ['ITC.id'], ),
    sa.ForeignKeyConstraint(['check_generic'], ['Check_generic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Deliverable_check_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ITC_check_id', sa.Integer(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('completion_datetime', sa.DateTime(), nullable=True),
    sa.Column('completion_by_user_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ITC_check_id'], ['ITC_check_map.id'], ),
    sa.ForeignKeyConstraint(['completion_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ITC', sa.Column('deliverable_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ITC', 'deliverable_type', ['deliverable_type_id'], ['id'])
    op.drop_column('ITC', 'comment')
    op.drop_column('ITC', 'percentage_complete')
    op.drop_column('ITC', 'status')
    op.drop_column('deliverable', 'percentage_complete')
    op.drop_column('deliverable', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverable', sa.Column('status', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('deliverable', sa.Column('percentage_complete', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ITC', sa.Column('status', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('ITC', sa.Column('percentage_complete', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ITC', sa.Column('comment', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'ITC', type_='foreignkey')
    op.drop_column('ITC', 'deliverable_type_id')
    op.drop_table('Deliverable_check_map')
    op.drop_table('ITC_check_map')
    op.drop_table('Check_generic')
    # ### end Alembic commands ###
