"""empty message

Revision ID: 391df9fcbbca
Revises: 
Create Date: 2017-05-04 04:15:10.290910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391df9fcbbca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbAlarmsEvents',
    sa.Column('SeqNo', sa.BigInteger(), nullable=False),
    sa.Column('UniqueAlarmId', sa.String(length=50), nullable=True),
    sa.Column('TriggeredTimestamp', sa.DateTime(), nullable=True),
    sa.Column('MonitoredPoint', sa.String(length=1024), nullable=True),
    sa.Column('AlarmState', sa.Integer(), nullable=True),
    sa.Column('AlarmText', sa.String(length=1024), nullable=True),
    sa.Column('Category', sa.String(length=128), nullable=True),
    sa.Column('Count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('SeqNo')
    )
    op.drop_table('status')
    op.alter_column('asset', 'Health',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('asset', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('asset', 'Priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('asset', 'Site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('asset', 'Type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('asset_point', 'Asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('asset_point', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('asset_point', 'PointType_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('asset_type', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('functional_descriptor', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('inbuildings_config', 'Site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issue_history', 'Issues',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issue_history', 'Site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issue_history', 'Timestamp_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issue_history_timestamp', 'Timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('point_type', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.add_column('result', sa.Column('Acknowledged', sa.Boolean(), nullable=True))
    op.add_column('result', sa.Column('Active', sa.Boolean(), nullable=True))
    op.add_column('result', sa.Column('First_timestamp', sa.DateTime(), nullable=False))
    op.add_column('result', sa.Column('Notes', sa.Text(), nullable=True))
    op.add_column('result', sa.Column('Occurances', sa.Integer(), nullable=False))
    op.add_column('result', sa.Column('Recent_timestamp', sa.DateTime(), nullable=False))
    op.alter_column('result', 'Algorithm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result', 'Asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result', 'Result',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'Status_id')
    op.drop_column('result', 'Timestamp')
    op.alter_column('site', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.add_column('result', sa.Column('Timestamp', sa.DATETIME(), nullable=True))
    op.add_column('result', sa.Column('Status_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'result', 'status', ['Status_id'], ['ID'])
    op.alter_column('result', 'Result',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('result', 'Asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result', 'Algorithm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('result', 'Recent_timestamp')
    op.drop_column('result', 'Occurances')
    op.drop_column('result', 'Notes')
    op.drop_column('result', 'First_timestamp')
    op.drop_column('result', 'Active')
    op.drop_column('result', 'Acknowledged')
    op.alter_column('point_type', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('issue_history_timestamp', 'Timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('issue_history', 'Timestamp_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('issue_history', 'Site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('issue_history', 'Issues',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inbuildings_config', 'Site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('functional_descriptor', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('asset_type', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('asset_point', 'PointType_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('asset_point', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('asset_point', 'Asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('asset', 'Type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('asset', 'Site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('asset', 'Priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('asset', 'Name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('asset', 'Health',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.create_table('status',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Descr', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('tbAlarmsEvents')
    # ### end Alembic commands ###
