"""empty message

Revision ID: 3965209e0c1e
Revises: 5d4d51baed59
Create Date: 2017-07-20 14:25:14.796066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3965209e0c1e'
down_revision = '5d4d51baed59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Deliverable_ITC_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=True),
    sa.Column('ITC_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ITC_id'], ['ITC.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('ITC_ibfk_1', 'ITC', type_='foreignkey')
    op.drop_column('ITC', 'deliverable_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ITC', sa.Column('deliverable_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('ITC_ibfk_1', 'ITC', 'deliverable', ['deliverable_id'], ['id'], ondelete='CASCADE')
    op.drop_table('Deliverable_ITC_map')
    # ### end Alembic commands ###
