"""empty message

Revision ID: 431b645e5942
Revises: 83df911f516c
Create Date: 2017-11-27 16:32:22.747956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '431b645e5942'
down_revision = '83df911f516c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_ibfk_2', 'location', type_='foreignkey')
    op.drop_column('location', 'secondary_location_id')
    op.add_column('secondary_location', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'secondary_location', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'secondary_location', type_='foreignkey')
    op.drop_column('secondary_location', 'location_id')
    op.add_column('location', sa.Column('secondary_location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('location_ibfk_2', 'location', 'secondary_location', ['secondary_location_id'], ['id'])
    # ### end Alembic commands ###
