"""empty message

Revision ID: 43816608680d
Revises: 99c9ad816ea9
Create Date: 2017-08-24 13:29:21.058170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43816608680d'
down_revision = '99c9ad816ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('it_asset',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minion_name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('minion_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('it_asset')
    # ### end Alembic commands ###
