"""empty message

Revision ID: 44bb979a8c3a
Revises: 323888a025be
Create Date: 2017-11-27 14:04:28.353982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44bb979a8c3a'
down_revision = '323888a025be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secondary_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('location', sa.Column('secondary_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'secondary_location', ['secondary_location_id'], ['id'])
    op.drop_column('location', 'secondary_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('secondary_location', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'secondary_location_id')
    op.drop_table('secondary_location')
    # ### end Alembic commands ###
