"""empty message

Revision ID: 5ca400180ce4
Revises: ab57035db6ed
Create Date: 2017-07-17 11:20:47.339329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca400180ce4'
down_revision = 'ab57035db6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ITC', sa.Column('status', sa.String(length=200), nullable=True))
    op.add_column('ITC_check_map', sa.Column('status', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ITC_check_map', 'status')
    op.drop_column('ITC', 'status')
    # ### end Alembic commands ###
