"""empty message

Revision ID: 5d4d51baed59
Revises: b371d20ef9b5
Create Date: 2017-07-18 09:08:19.233850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d4d51baed59'
down_revision = 'b371d20ef9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ITC_check_map', 'percentage_complete')
    op.add_column('ITP', sa.Column('percentage_complete', sa.Integer(), nullable=True))
    op.add_column('ITP', sa.Column('status', sa.String(length=200), nullable=True))
    op.add_column('deliverable', sa.Column('percentage_complete', sa.Integer(), nullable=True))
    op.add_column('deliverable', sa.Column('status', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliverable', 'status')
    op.drop_column('deliverable', 'percentage_complete')
    op.drop_column('ITP', 'status')
    op.drop_column('ITP', 'percentage_complete')
    op.add_column('ITC_check_map', sa.Column('percentage_complete', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
