"""empty message

Revision ID: 6299e534470c
Revises: b5fce3098ced
Create Date: 2017-08-19 17:51:23.323742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6299e534470c'
down_revision = 'b5fce3098ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_data_uploader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('aws_username', sa.String(length=100), nullable=False),
    sa.Column('aws_access_key_id', sa.String(length=100), nullable=True),
    sa.Column('aws_secret_access_key', sa.String(length=100), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.ID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aws_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_data_uploader')
    # ### end Alembic commands ###
