"""empty message

Revision ID: 64e53bf9f77d
Revises: a3665d5105f1
Create Date: 2017-05-14 16:27:50.165211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64e53bf9f77d'
down_revision = 'a3665d5105f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('MonitoredPoint', sa.String(length=1024), nullable=True))
    op.drop_column('alarm', 'MonitoredPoInteger')
    op.add_column('tbAlarmsEvents', sa.Column('MonitoredPoint', sa.String(length=1024), nullable=True))
    op.drop_column('tbAlarmsEvents', 'MonitoredPoInteger')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbAlarmsEvents', sa.Column('MonitoredPoInteger', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('tbAlarmsEvents', 'MonitoredPoint')
    op.add_column('alarm', sa.Column('MonitoredPoInteger', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('alarm', 'MonitoredPoint')
    # ### end Alembic commands ###
