"""empty message

Revision ID: 6d74e87630bd
Revises: 3c91f5965f1f
Create Date: 2017-05-05 06:39:04.944417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d74e87630bd'
down_revision = '3c91f5965f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'Health',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('asset', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('asset', 'Priority',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('asset', 'Site_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('asset', 'Type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('asset_point', 'Asset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('asset_point', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('asset_point', 'PointType_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('asset_type', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('functional_descriptor', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('inbuildings_config', 'Site_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('issue_history', 'Issues',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('issue_history', 'Site_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('issue_history', 'Timestamp_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('issue_history_timestamp', 'Timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('point_type', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.add_column('result', sa.Column('Priority', sa.Integer(), nullable=False))
    op.alter_column('result', 'Algorithm_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('result', 'Asset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('result', 'First_timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('result', 'Occurances',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('result', 'Recent_timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('result', 'Result',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.add_column('site', sa.Column('CMMS_trigger_priority', sa.Integer(), nullable=True))
    op.add_column('site', sa.Column('Email_trigger_priority', sa.Integer(), nullable=True))
    op.alter_column('site', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.drop_column('site', 'Email_trigger_priority')
    op.drop_column('site', 'CMMS_trigger_priority')
    op.alter_column('result', 'Result',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('result', 'Recent_timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('result', 'Occurances',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('result', 'First_timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('result', 'Asset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('result', 'Algorithm_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('result', 'Priority')
    op.alter_column('point_type', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('issue_history_timestamp', 'Timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('issue_history', 'Timestamp_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('issue_history', 'Site_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('issue_history', 'Issues',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('inbuildings_config', 'Site_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('functional_descriptor', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('asset_type', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('asset_point', 'PointType_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('asset_point', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('asset_point', 'Asset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('asset', 'Type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('asset', 'Site_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('asset', 'Priority',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('asset', 'Name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('asset', 'Health',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
