"""empty message

Revision ID: 7678021557c5
Revises: a4d73c83c5e2
Create Date: 2017-12-01 08:43:54.544797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7678021557c5'
down_revision = 'a4d73c83c5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ITC_check_map', sa.Column('check_number', sa.Integer(), nullable=True))
    op.drop_column('ITC_group', 'check_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ITC_group', sa.Column('check_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('ITC_check_map', 'check_number')
    # ### end Alembic commands ###
