"""empty message

Revision ID: 8406974fb81b
Revises: 18ec21bbf18b
Create Date: 2017-09-04 09:32:41.360383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8406974fb81b'
down_revision = '18ec21bbf18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_component', sa.Column('name', sa.String(length=20), nullable=True))
    op.drop_column('ticket_component', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_component', sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('ticket_component', 'name')
    # ### end Alembic commands ###
