"""empty message

Revision ID: 915f8dff4f7d
Revises: a2d3b511b22d
Create Date: 2017-09-19 14:15:46.167271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915f8dff4f7d'
down_revision = 'a2d3b511b22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_site_name_uc', 'project', ['site_id', 'name'])
    op.create_unique_constraint(None, 'site', ['Name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint('_site_name_uc', 'project', type_='unique')
    # ### end Alembic commands ###
