"""empty message

Revision ID: 99c9ad816ea9
Revises: cc8e0187b46a
Create Date: 2017-08-22 09:19:30.903780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c9ad816ea9'
down_revision = 'cc8e0187b46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverable', sa.Column('assigned_to', sa.String(length=255), nullable=True))
    op.add_column('deliverable', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('deliverable', sa.Column('completion_date', sa.DateTime(), nullable=True))
    op.add_column('deliverable', sa.Column('component_number', sa.Integer(), nullable=True))
    op.add_column('deliverable', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliverable', 'start_date')
    op.drop_column('deliverable', 'component_number')
    op.drop_column('deliverable', 'completion_date')
    op.drop_column('deliverable', 'completed')
    op.drop_column('deliverable', 'assigned_to')
    # ### end Alembic commands ###
