"""empty message

Revision ID: 9ae8c06b1eed
Revises: 065f64b7c8c6
Create Date: 2017-08-09 10:06:01.133868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ae8c06b1eed'
down_revision = '065f64b7c8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('current_login_ip', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.drop_column('user', 'email_confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'current_login_ip')
    op.drop_column('user', 'current_login_at')
    # ### end Alembic commands ###
