"""empty message

Revision ID: a2d3b511b22d
Revises: 8406974fb81b
Create Date: 2017-09-08 13:29:13.671953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2d3b511b22d'
down_revision = '8406974fb81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_resolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('flicket_topic', sa.Column('resolution_id', sa.Integer(), nullable=True))
    op.alter_column('flicket_topic', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'flicket_topic', 'ticket_resolution', ['resolution_id'], ['id'])
    op.drop_column('flicket_topic', 'resolution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flicket_topic', sa.Column('resolution', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'flicket_topic', type_='foreignkey')
    op.alter_column('flicket_topic', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('flicket_topic', 'resolution_id')
    op.drop_table('ticket_resolution')
    # ### end Alembic commands ###
