"""empty message

Revision ID: a4d73c83c5e2
Revises: 431b645e5942
Create Date: 2017-12-01 08:42:36.041914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d73c83c5e2'
down_revision = '431b645e5942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverable_ITC_map', sa.Column('ITC_group_number', sa.Integer(), nullable=True))
    op.add_column('ITC_group', sa.Column('check_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ITC_group', 'check_number')
    op.drop_column('Deliverable_ITC_map', 'ITC_group_number')
    # ### end Alembic commands ###
