"""empty message

Revision ID: a989f414cebc
Revises: 364ce7e16831
Create Date: 2017-07-24 14:40:28.817318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a989f414cebc'
down_revision = '364ce7e16831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliverable', sa.Column('percentage_complete', sa.Integer(), nullable=True))
    op.add_column('deliverable', sa.Column('status', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliverable', 'status')
    op.drop_column('deliverable', 'percentage_complete')
    # ### end Alembic commands ###
