"""empty message

Revision ID: ab57035db6ed
Revises: 13e740e65cc2
Create Date: 2017-07-13 11:55:49.519122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab57035db6ed'
down_revision = '13e740e65cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Check_generic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ITC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('deliverable_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ITC_check_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_generic', sa.Integer(), nullable=True),
    sa.Column('ITC_id', sa.Integer(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('completion_datetime', sa.DateTime(), nullable=True),
    sa.Column('completion_by_user_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ITC_id'], ['ITC.id'], ),
    sa.ForeignKeyConstraint(['check_generic'], ['Check_generic.id'], ),
    sa.ForeignKeyConstraint(['completion_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'ITP', ['name'])
    op.add_column('project', sa.Column('description', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'project', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'description')
    op.drop_constraint(None, 'ITP', type_='unique')
    op.drop_table('ITC_check_map')
    op.drop_table('ITC')
    op.drop_table('Check_generic')
    # ### end Alembic commands ###
