"""empty message

Revision ID: ae843d17da36
Revises: 43816608680d
Create Date: 2017-08-24 15:48:16.793583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae843d17da36'
down_revision = '43816608680d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flicket_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['flicket_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_due', sa.DateTime(), nullable=True),
    sa.Column('started_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('component', sa.String(length=128), nullable=True),
    sa.Column('ticket_priority_id', sa.Integer(), nullable=True),
    sa.Column('assigned_id', sa.Integer(), nullable=True),
    sa.Column('date_resolved', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=128), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('facility', sa.String(length=128), nullable=True),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('modified_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['flicket_category.id'], ),
    sa.ForeignKeyConstraint(['modified_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['started_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['flicket_status.id'], ),
    sa.ForeignKeyConstraint(['ticket_priority_id'], ['flicket_priorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flicket_topic_ticket_name'), 'flicket_topic', ['ticket_name'], unique=False)
    op.create_table('flicket_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('modified_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modified_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['flicket_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_ticket_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['flicket_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('original_content', sa.String(length=5000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['flicket_post.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['flicket_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_ticket_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.Column('claimed', sa.Boolean(), nullable=True),
    sa.Column('released', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['flicket_post.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['flicket_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('original_filename', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['flicket_post.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['flicket_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flicket_uploads')
    op.drop_table('flicket_ticket_action')
    op.drop_table('flicket_history')
    op.drop_table('flicket_ticket_subscription')
    op.drop_table('flicket_post')
    op.drop_index(op.f('ix_flicket_topic_ticket_name'), table_name='flicket_topic')
    op.drop_table('flicket_topic')
    op.drop_table('flicket_category')
    op.drop_table('flicket_status')
    op.drop_table('flicket_priorities')
    op.drop_table('flicket_department')
    # ### end Alembic commands ###
