"""empty message

Revision ID: b371d20ef9b5
Revises: 5ca400180ce4
Create Date: 2017-07-17 13:23:23.928138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b371d20ef9b5'
down_revision = '5ca400180ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ITC', sa.Column('percentage_complete', sa.Integer(), nullable=True))
    op.add_column('ITC_check_map', sa.Column('percentage_complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ITC_check_map', 'percentage_complete')
    op.drop_column('ITC', 'percentage_complete')
    # ### end Alembic commands ###
