"""empty message

Revision ID: b5fce3098ced
Revises: 9ae8c06b1eed
Create Date: 2017-08-09 15:35:32.320999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5fce3098ced'
down_revision = '9ae8c06b1eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False))
    op.create_index('username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###
