"""empty message

Revision ID: be06303bb8e1
Revises: 83242f8e3379
Create Date: 2017-12-05 15:56:21.072611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be06303bb8e1'
down_revision = '83242f8e3379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverable_ITC_map', sa.Column('maintenance_revision_number', sa.Integer(), nullable=True))
    op.add_column('Deliverable_ITC_map', sa.Column('major_revision_number', sa.Integer(), nullable=True))
    op.add_column('Deliverable_ITC_map', sa.Column('minor_revision_number', sa.Integer(), nullable=True))
    op.add_column('ITC_group', sa.Column('short_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ITC_group', 'short_name')
    op.drop_column('Deliverable_ITC_map', 'minor_revision_number')
    op.drop_column('Deliverable_ITC_map', 'major_revision_number')
    op.drop_column('Deliverable_ITC_map', 'maintenance_revision_number')
    # ### end Alembic commands ###
