"""empty message

Revision ID: c90098cd1ce1
Revises: 37c30892cad0
Create Date: 2017-07-21 19:51:27.983533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90098cd1ce1'
down_revision = '37c30892cad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverable_check_map', sa.Column('deliverable_ITC_map_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Deliverable_check_map', 'Deliverable_ITC_map', ['deliverable_ITC_map_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Deliverable_check_map', type_='foreignkey')
    op.drop_column('Deliverable_check_map', 'deliverable_ITC_map_id')
    # ### end Alembic commands ###
