"""empty message

Revision ID: dbbbdc9fa66f
Revises: 18f4984e31d9
Create Date: 2017-09-01 09:48:31.668780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbbbdc9fa66f'
down_revision = '18f4984e31d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['assigned_to_id'], ['id'])
    op.drop_column('project', 'assigned_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('assigned_to', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'assigned_to_id')
    # ### end Alembic commands ###
