"""empty message

Revision ID: e5051545a293
Revises: 2a96b005210f
Create Date: 2017-11-26 14:15:07.311314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5051545a293'
down_revision = '2a96b005210f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ITC_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('Deliverable_ITC_map', sa.Column('comments', sa.String(length=255), nullable=False))
    op.add_column('ITC', sa.Column('ITC_group_id', sa.Integer(), nullable=True))
    op.add_column('ITC', sa.Column('description', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'ITC', 'ITC_group', ['ITC_group_id'], ['id'])
    op.add_column('ITP', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('location', sa.Column('secondary_location', sa.String(length=255), nullable=False))
    op.add_column('location', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'site', ['site_id'], ['ID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'site_id')
    op.drop_column('location', 'secondary_location')
    op.drop_column('ITP', 'description')
    op.drop_constraint(None, 'ITC', type_='foreignkey')
    op.drop_column('ITC', 'description')
    op.drop_column('ITC', 'ITC_group_id')
    op.drop_column('Deliverable_ITC_map', 'comments')
    op.drop_table('ITC_group')
    # ### end Alembic commands ###
