"""empty message

Revision ID: e922ab2bd828
Revises: 25d20f5036bb
Create Date: 2017-08-27 13:55:51.383537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e922ab2bd828'
down_revision = '25d20f5036bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('it_asset', sa.Column('minion_key_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('it_asset', 'minion_key_accepted')
    # ### end Alembic commands ###
