"""empty message

Revision ID: e92f4d9b52ef
Revises: c90098cd1ce1
Create Date: 2017-07-24 14:29:26.183896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92f4d9b52ef'
down_revision = 'c90098cd1ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deliverable_ITC_map', sa.Column('status', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Deliverable_ITC_map', 'status')
    # ### end Alembic commands ###
