"""empty message

Revision ID: ebecbb6a8b4e
Revises: 979606e09a0d
Create Date: 2017-05-31 16:07:09.213023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebecbb6a8b4e'
down_revision = '979606e09a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'DisabledBy')
    op.drop_column('alarm', 'PreviousAlarmState')
    op.drop_column('alarm', 'OriginatedGUID')
    op.drop_column('alarm', 'AlarmType')
    op.drop_column('alarm', 'Module')
    op.drop_column('alarm', 'AlarmStateSeqNo')
    op.drop_column('alarm', 'Category')
    op.drop_column('alarm', 'PendingCommand')
    op.drop_column('alarm', 'CheckedSteps')
    op.drop_column('alarm', 'TriggeredTimestamp')
    op.drop_column('alarm', 'PendingState')
    op.drop_column('alarm', 'BasicEvaluationState')
    op.drop_column('alarm', 'FlashingAlert')
    op.drop_column('alarm', 'DateTimeStamp')
    op.drop_column('alarm', 'AssignState')
    op.drop_column('alarm', 'AssignedTo')
    op.drop_column('alarm', 'Command')
    op.drop_column('alarm', 'Logging')
    op.drop_column('alarm', 'MonitoredValue')
    op.drop_column('alarm', 'UniqueAlarmId')
    op.drop_column('alarm', 'HasAttachment')
    op.drop_column('alarm', 'SeqNo')
    op.drop_column('alarm', 'AcknowledgedBy')
    op.drop_column('alarm', 'AlarmText')
    op.drop_column('alarm', 'AcknowledgeTime')
    op.drop_column('alarm', 'Count')
    op.drop_column('alarm', 'AlarmState')
    op.drop_column('alarm', 'AudibleAlert')
    op.drop_column('alarm', 'SystemAlarmId')
    op.drop_column('alarm', 'SystemEventId')
    op.drop_column('alarm', 'Silence')
    op.drop_column('alarm', 'Priority')
    op.drop_column('alarm', 'Hidden')
    op.drop_column('alarm', 'AdvancedEvaluationState')
    op.drop_column('alarm', 'MonitoredPoint')
    op.drop_column('alarm', 'DomainName')
    op.drop_column('alarm', 'ServerOffline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('ServerOffline', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('DomainName', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('alarm', sa.Column('MonitoredPoint', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('alarm', sa.Column('AdvancedEvaluationState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('Hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('Priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('Silence', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('SystemEventId', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('SystemAlarmId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('AudibleAlert', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('AlarmState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('Count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('AcknowledgeTime', mysql.DATETIME(), nullable=True))
    op.add_column('alarm', sa.Column('AlarmText', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('alarm', sa.Column('AcknowledgedBy', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('alarm', sa.Column('SeqNo', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('HasAttachment', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('UniqueAlarmId', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('alarm', sa.Column('MonitoredValue', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('alarm', sa.Column('Logging', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('Command', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('alarm', sa.Column('AssignedTo', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('alarm', sa.Column('AssignState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('DateTimeStamp', mysql.DATETIME(), nullable=True))
    op.add_column('alarm', sa.Column('FlashingAlert', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('BasicEvaluationState', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('PendingState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('TriggeredTimestamp', mysql.DATETIME(), nullable=True))
    op.add_column('alarm', sa.Column('CheckedSteps', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('alarm', sa.Column('PendingCommand', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('Category', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('alarm', sa.Column('AlarmStateSeqNo', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('Module', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('AlarmType', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('alarm', sa.Column('OriginatedGUID', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('alarm', sa.Column('PreviousAlarmState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('alarm', sa.Column('DisabledBy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
