"""empty message

Revision ID: f7eacb2f132a
Revises: a989f414cebc
Create Date: 2017-07-25 15:27:23.997346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7eacb2f132a'
down_revision = 'a989f414cebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ITC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('deliverable_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deliverable_type_id'], ['deliverable_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ITC_check_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_generic', sa.Integer(), nullable=True),
    sa.Column('ITC_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ITC_id'], ['ITC.id'], ),
    sa.ForeignKeyConstraint(['check_generic'], ['Check_generic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Deliverable_ITC_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=True),
    sa.Column('ITC_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('percentage_complete', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ITC_id'], ['ITC.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Deliverable_check_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_ITC_map_id', sa.Integer(), nullable=True),
    sa.Column('ITC_check_id', sa.Integer(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('completion_datetime', sa.DateTime(), nullable=True),
    sa.Column('completion_by_user_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ITC_check_id'], ['ITC_check_map.id'], ),
    sa.ForeignKeyConstraint(['completion_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deliverable_ITC_map_id'], ['Deliverable_ITC_map.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Deliverable_check_map')
    op.drop_table('Deliverable_ITC_map')
    op.drop_table('ITC_check_map')
    op.drop_table('ITC')
    # ### end Alembic commands ###
