"""empty message

Revision ID: ff9c214dc46e
Revises: 80237cc6d863
Create Date: 2017-05-31 16:41:09.453296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff9c214dc46e'
down_revision = '80237cc6d863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm',
    sa.Column('site_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('AcknowledgeTime', mysql.DATETIME(), nullable=True),
    sa.Column('AcknowledgedBy', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('AdvancedEvaluationState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AlarmState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AlarmStateSeqNo', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('AlarmText', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('AlarmType', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('AssignState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AssignedTo', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('AudibleAlert', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('BasicEvaluationState', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Category', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('CheckedSteps', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('Command', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('DateTimeStamp', mysql.DATETIME(), nullable=True),
    sa.Column('DisabledBy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('DomainName', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('FlashingAlert', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('HasAttachment', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Logging', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Medusa_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Module', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('MonitoredPoint', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('MonitoredValue', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('OriginatedGUID', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('PendingCommand', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('PendingState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('PreviousAlarmState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('SeqNo', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('ServerOffline', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Silence', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('SystemAlarmId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('SystemEventId', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('TriggeredTimestamp', mysql.DATETIME(), nullable=True),
    sa.Column('UniqueAlarmId', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.ID'], name='alarm_ibfk_1'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
