"""empty message

Revision ID: 0b651b5fd8e6
Revises: 6d74e87630bd
Create Date: 2017-05-08 00:32:14.373227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b651b5fd8e6'
down_revision = '6d74e87630bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Address', sa.String(length=512), nullable=True),
    sa.Column('Site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Site_id'], ['site.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
