"""empty message

Revision ID: 172bde483658
Revises: a0a6a2818389
Create Date: 2017-05-31 11:44:29.082071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '172bde483658'
down_revision = 'a0a6a2818389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_time_value',
    sa.Column('Medusa_ID', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('DateTimeStamp', sa.DateTime(), nullable=True),
    sa.Column('SeqNo', sa.BigInteger(), nullable=True),
    sa.Column('FloatVALUE', sa.Float(), nullable=True),
    sa.Column('ParentID', sa.Integer(), nullable=True),
    sa.Column('OdometerValue', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.ID'], ),
    sa.PrimaryKeyConstraint('Medusa_ID')
    )
    op.create_table('logged_entity',
    sa.Column('Medusa_ID', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('ID', sa.Integer(), nullable=True),
    sa.Column('GUID', sa.String(length=50), nullable=True),
    sa.Column('Path', sa.String(length=1024), nullable=True),
    sa.Column('Descr', sa.String(length=512), nullable=True),
    sa.Column('Disabled', sa.Boolean(), nullable=True),
    sa.Column('LastMod', sa.DateTime(), nullable=True),
    sa.Column('Version', sa.Integer(), nullable=True),
    sa.Column('Type', sa.String(length=80), nullable=True),
    sa.Column('LogPoint', sa.String(length=1024), nullable=True),
    sa.Column('UNITPREFIX', sa.String(length=512), nullable=True),
    sa.Column('Unit', sa.String(length=512), nullable=True),
    sa.Column('BaseValue', sa.Float(), nullable=True),
    sa.Column('MeterStartPoint', sa.Float(), nullable=True),
    sa.Column('LastReadValue', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.ID'], ),
    sa.PrimaryKeyConstraint('Medusa_ID')
    )
    op.drop_table('tbLogTimeValues')
    op.drop_table('tbLoggedEntities')
    op.add_column('alarm', sa.Column('Medusa_ID', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'Medusa_ID')
    op.create_table('tbLoggedEntities',
    sa.Column('ID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('GUID', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Path', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('Descr', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('Disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('LastMod', mysql.DATETIME(), nullable=True),
    sa.Column('Version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Type', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('LogPoint', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('UNITPREFIX', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('Unit', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('BaseValue', mysql.FLOAT(), nullable=True),
    sa.Column('MeterStartPoint', mysql.FLOAT(), nullable=True),
    sa.Column('LastReadValue', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tbLogTimeValues',
    sa.Column('DateTimeStamp', mysql.DATETIME(), nullable=True),
    sa.Column('SeqNo', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('FloatVALUE', mysql.FLOAT(), nullable=True),
    sa.Column('ParentID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('OdometerValue', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('SeqNo', 'ParentID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('logged_entity')
    op.drop_table('log_time_value')
    # ### end Alembic commands ###
