"""empty message

Revision ID: 5e6e3fb61ac5
Revises: ebecbb6a8b4e
Create Date: 2017-05-31 16:17:18.203078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e6e3fb61ac5'
down_revision = 'ebecbb6a8b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('xMedusa_ID', sa.Integer(), nullable=False))
    op.drop_column('alarm', 'Medusa_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('Medusa_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('alarm', 'xMedusa_ID')
    # ### end Alembic commands ###
