"""empty message

Revision ID: 7082a469fba9
Revises: fb62c29674eb
Create Date: 2017-04-27 07:06:06.700215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7082a469fba9'
down_revision = 'fb62c29674eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('Active1', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'Active1')
    # ### end Alembic commands ###
