"""empty message

Revision ID: 9212d448882f
Revises: f2f9a140b061
Create Date: 2017-05-09 14:35:27.950155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9212d448882f'
down_revision = 'f2f9a140b061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.Unicode(length=255), server_default='', nullable=False))
    op.drop_index('email', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
