"""empty message

Revision ID: a0a6a2818389
Revises: 64e53bf9f77d
Create Date: 2017-05-17 16:08:34.986913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0a6a2818389'
down_revision = '64e53bf9f77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functional_descriptor_category',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('function_category_type_mapping',
    sa.Column('Type_id', sa.Integer(), nullable=False),
    sa.Column('FunctionalDescriptorCategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FunctionalDescriptorCategory_id'], ['functional_descriptor_category.ID'], ),
    sa.ForeignKeyConstraint(['Type_id'], ['asset_type.ID'], ),
    sa.PrimaryKeyConstraint('Type_id', 'FunctionalDescriptorCategory_id')
    )
    op.add_column('functional_descriptor', sa.Column('Category_id', sa.Integer(), nullable=True))
    op.drop_constraint('functional_descriptor_ibfk_1', 'functional_descriptor', type_='foreignkey')
    op.create_foreign_key(None, 'functional_descriptor', 'functional_descriptor_category', ['Category_id'], ['ID'])
    op.drop_column('functional_descriptor', 'Type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functional_descriptor', sa.Column('Type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'functional_descriptor', type_='foreignkey')
    op.create_foreign_key('functional_descriptor_ibfk_1', 'functional_descriptor', 'asset_type', ['Type_id'], ['ID'])
    op.drop_column('functional_descriptor', 'Category_id')
    op.drop_table('function_category_type_mapping')
    op.drop_table('functional_descriptor_category')
    # ### end Alembic commands ###
